version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cgc-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1luxf9hd2vzqb"
s3_prefix = "cgc-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

